In [50]:
import numpy as np
import scipy.stats as stats
import pandas as pd
import sklearn.metrics 

# Exercises

## 2. Given a confusion matrix between actual/predicted dog/casts, evaluate performance

### Whats a false positive?

FP: They predicted dog, but its actually a cat, 13 in this matrix

### What is a false negative?

FN: They predicted cat, but its actually a dog. 7 in this matrix

## 3. You are working as a datascientist working for Codeup Cody Creator (C3 for short), a rubber-duck manufacturing plant. Answer the following questions

### An internal team wants to investigate the cause of the manufacturing defects. They tell you that they want to identify as many of the ducks that have a defect as possible. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

In [4]:
df_c3 = pd.read_csv('c3.csv')
df_c3

actual     model1     model2     model3
0    No Defect  No Defect     Defect  No Defect
1    No Defect  No Defect     Defect     Defect
2    No Defect  No Defect     Defect  No Defect
3    No Defect     Defect     Defect     Defect
4    No Defect  No Defect     Defect  No Defect
..         ...        ...        ...        ...
195  No Defect  No Defect     Defect     Defect
196     Defect     Defect  No Defect  No Defect
197  No Defect  No Defect  No Defect  No Defect
198  No Defect  No Defect     Defect     Defect
199  No Defect  No Defect  No Defect     Defect

[200 rows x 4 columns]

In [8]:
matrix1 = confusion_matrix(df_c3.actual, df_c3.model1)
matrix1.

array([[  8,   8],
       [  2, 182]])

In [9]:
matrix2 = confusion_matrix(df_c3.actual, df_c3.model2)
matrix2

array([[  9,   7],
       [ 81, 103]])

In [10]:
matrix3 = confusion_matrix(df_c3.actual, df_c3.model3)
matrix3

array([[13,  3],
       [86, 98]])

In [11]:
df_c3.actual.value_counts()

No Defect    184
Defect        16
Name: actual, dtype: int64

In [13]:
df_c3['baseline'] = 'No Defect'
df_c3

actual     model1     model2     model3   baseline
0    No Defect  No Defect     Defect  No Defect  No Defect
1    No Defect  No Defect     Defect     Defect  No Defect
2    No Defect  No Defect     Defect  No Defect  No Defect
3    No Defect     Defect     Defect     Defect  No Defect
4    No Defect  No Defect     Defect  No Defect  No Defect
..         ...        ...        ...        ...        ...
195  No Defect  No Defect     Defect     Defect  No Defect
196     Defect     Defect  No Defect  No Defect  No Defect
197  No Defect  No Defect  No Defect  No Defect  No Defect
198  No Defect  No Defect     Defect     Defect  No Defect
199  No Defect  No Defect  No Defect     Defect  No Defect

[200 rows x 5 columns]

In [17]:
model1_accuracy = (df_c3.model1 == df_c3.actual).mean()
baseline_accuracy = (df_c3.baseline == df_c3.actual).mean()
print(model1_accuracy)
print(baseline_accuracy)

0.95
0.92


In [19]:
model2_accuracy = (df_c3.model2 == df_c3.actual).mean()
model2_accuracy

0.56

In [20]:
model3_accuracy = (df_c3.model3 == df_c3.actual).mean()
model3_accuracy

0.555

The evaluation metrics I would choose would be specificity and false positive rate using model 1. It has the highest true positive rate(no defects, acccurately detected) , but we want to identify as many of the fasle positives (ones that have defects but arent detected) and true negatives(detected ducks with defects) as possible. False negatives aren't too important because a rubber duck is cheap.

### Recently several stories in the local news have come out highlighting customers who received a rubber duck with a defect, and portraying C3 in a bad light. The PR team has decided to launch a program that gives customers with a defective duck a vacation to Hawaii. They need you to predict which ducks will have defects, but tell you the really don't want to accidentally give out a vacation package when the duck really doesn't have a defect. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

I would go with false positive rate on model 1. Model 1 has a 5% misclassification rate, and false positive rates focuses on the ducks that missed the model and would be shipped out to customers. any duck that gets shipped to a customer costs the company a trip to hawaii. 

## 4. You are working as a data scientist for Gives You Paws ™, a subscription based service that shows you cute pictures of dogs or cats (or both for an additional fee). At Gives You Paws, anyone can upload pictures of their cats or dogs. The photos are then put through a two step process. First an automated algorithm tags pictures as either a cat or a dog (Phase I). Next, the photos that have been initially identified are put through another round of review, possibly with some human oversight, before being presented to the users (Phase II). Given this dataset, use pandas to create a baseline model (i.e. a model that just predicts the most common class) and answer the following questions:



### a. In terms of accuracy, how do the various models compare to the baseline model? Are any of the models better than the baseline?


In [21]:
df_paw = pd.read_csv('gives_you_paws.csv')

In [25]:
df_paw.actual.value_counts()

dog    3254
cat    1746
Name: actual, dtype: int64

In [28]:
df_paw['baseline'] = 'dog'
df_paw

actual model1 model2 model3 model4 baseline
0       cat    cat    dog    cat    dog      dog
1       dog    dog    cat    cat    dog      dog
2       dog    cat    cat    cat    dog      dog
3       dog    dog    dog    cat    dog      dog
4       cat    cat    cat    dog    dog      dog
...     ...    ...    ...    ...    ...      ...
4995    dog    dog    dog    dog    dog      dog
4996    dog    dog    cat    cat    dog      dog
4997    dog    cat    cat    dog    dog      dog
4998    cat    cat    cat    cat    dog      dog
4999    dog    dog    dog    dog    dog      dog

[5000 rows x 6 columns]

In [30]:
paw_baseline = (df_paw.baseline == df_paw.actual).mean()
paw_baseline

0.6508

In [31]:
paw1 = (df_paw.model1 == df_paw.actual).mean()
paw1

0.8074

In [32]:
paw2 = (df_paw.model2 == df_paw.actual).mean()
paw2

0.6304

In [34]:
paw3 = (df_paw.model3 == df_paw.actual).mean()
paw3

0.5096

In [36]:
paw4 = (df_paw.model4 == df_paw.actual).mean()
paw4

0.7426

Both model 1 and model 4 are better than the baseline

### b. Suppose you are working on a team that solely deals with dog pictures. Which of these models would you recomend for Phase I? For Phase II?

In [38]:
pmatrix1 = confusion_matrix(df_paw.actual, df_paw.model1)
pmatrix1

array([[1423,  323],
       [ 640, 2614]])

In [39]:
pmatrix2 = confusion_matrix(df_paw.actual, df_paw.model2)
pmatrix2

array([[1555,  191],
       [1657, 1597]])

In [40]:
pmatrix3 = confusion_matrix(df_paw.actual, df_paw.model3)
pmatrix3

array([[ 893,  853],
       [1599, 1655]])

In [41]:
pmatrix4 = confusion_matrix(df_paw.actual, df_paw.model4)
pmatrix4

array([[ 603, 1143],
       [ 144, 3110]])

In [42]:
pd.crosstab(df_paw.actual, df_paw.model1)

model1   cat   dog
actual            
cat     1423   323
dog      640  2614

I would go with model 1, since it has the highest amount of true positives (ie. correctly identifed as dogs) and lowest in proportion of false positives for phase 1, so that the next phase has the highest amount of dog only photos going into it. Then I'd use model 1 to maximize true positives.

### c. Suppose you are working on a team that solely deals with cat pictures. Which of these models would you recomend for Phase I? For Phase II?

I would go with model 2 since it has a large rate of negative results, and then follow up with model 4 to identify the true negatives.

## Follow the links below to read the documentation about each function, then apply those functions to the data from the previous problem.

In [84]:
acc1 = sklearn.metrics.accuracy_score(df_paw.actual, df_paw.model1)
acc1

0.8074

In [77]:
acc2 = sklearn.metrics.accuracy_score(df_paw.actual, df_paw.model2)
acc2

0.6304

In [82]:
acc3 = sklearn.metrics.accuracy_score(df_paw.actual, df_paw.model3)
acc3

0.5096

In [81]:
acc4 = sklearn.metrics.accuracy_score(df_paw.actual, df_paw.model4)
acc4

0.7426

In [86]:
prec1 = sklearn.metrics.precision_score(df_paw.actual, df_paw.model1, pos_label = 'dog')
prec1

0.8900238338440586

In [88]:
prec2 = sklearn.metrics.precision_score(df_paw.actual, df_paw.model2, pos_label = 'dog')
prec2

0.8931767337807607

In [90]:
prec3 = sklearn.metrics.precision_score(df_paw.actual, df_paw.model3, pos_label = 'dog')
prec3

0.6598883572567783

In [93]:
prec4 = sklearn.metrics.precision_score(df_paw.actual, df_paw.model4, pos_label = 'dog')
prec4

0.7312485304490948

In [95]:
rec1 = sklearn.metrics.recall_score(df_paw.actual, df_paw.model1, pos_label = 'dog')
rec1

0.803318992009834

In [98]:
rec2 = sklearn.metrics.recall_score(df_paw.actual, df_paw.model2, pos_label = 'dog')
rec2

0.49078057775046097

In [100]:
rec3 = sklearn.metrics.recall_score(df_paw.actual, df_paw.model3, pos_label = 'dog')
rec3

0.5086047940995697

In [103]:
rec4 = sklearn.metrics.recall_score(df_paw.actual, df_paw.model4, pos_label = 'dog')
rec4

0.9557467732022127

In [106]:
cl1 = sklearn.metrics.classification_report(df_paw.actual, df_paw.model1)
print(cl1)

              precision    recall  f1-score   support

         cat       0.69      0.82      0.75      1746
         dog       0.89      0.80      0.84      3254

    accuracy                           0.81      5000
   macro avg       0.79      0.81      0.80      5000
weighted avg       0.82      0.81      0.81      5000



In [107]:
cl2 = sklearn.metrics.classification_report(df_paw.actual, df_paw.model2)
print(cl2)

              precision    recall  f1-score   support

         cat       0.48      0.89      0.63      1746
         dog       0.89      0.49      0.63      3254

    accuracy                           0.63      5000
   macro avg       0.69      0.69      0.63      5000
weighted avg       0.75      0.63      0.63      5000



In [ ]:
cl3 = sklearn.metrics.classification_report(df_paw.actual, df_paw.model1)
print(cl1)